# Please check the parameters, and adjust them according to your circumstance

## the path to fastq files
INPUTPATH: "data/example/fastq"

## paths for intermediate outputs
OUTPUTPATH: "data/example/trim"  # intermediate output. do not upload to github

## the meta file describing the experiment settings
METAFILE: "configs/metadata.tsv"

## is the sequencing paired-end or single-end?
END: "pair"

