# Please check the parameters, and adjust them according to your circumstance
INPUTPATH: "output/countFile"
OUTPUTPATH: "output/dea"
METAFILE: "configs/metadata.tsv"

PAIR: FALSE  # Is this a pair test or not? (TRUE or FALSE)

## The corresponding dataset in ENSEMBL for your interested organism
EnsemblDataSet: "hsapiens_gene_ensembl"  # search for your dataset in the file EnsemblDataSet_look_up_table.csv 

## the comparison(s) you want to do. If multiple comparisons, specify each pair (CONTROL & TREAT) in order respectively
CONTROL: ["Untreated"]
TREAT: ["Dexamethasone"]
## length of 'CONTROL' should agree with that of 'TREAT'
## what you fill in there should agree with the "group" column in metadata.tsv

FILTER:
  yesOrNo: TRUE  # Filter out low expressed genes or not? (TRUE or FALSE)
  cpm: 1  # if yes for filter, what's the threshold of cpm?
