# Please check the parameters, and adjust them according to your circumstance

# project name
PROJECT: test

## the path to fastq files
INPUTPATH: data/example/fastq_single

## paths for intermediate outputs
OUTPUTPATH: data/output  # intermediate output. do not upload to github

## the meta file describing the experiment settings
METAFILE: configs/metadata.tsv

## is the sequencing paired-end or single-end?
END: single  # "pair" or "single"

