# Please check the parameters, and adjust them according to your circumstance

# project name
PROJECT: test

INPUTPATH: output
OUTPUTPATH: output/transcript_level_only
METAFILE: configs/metadata.tsv

PAIR: FALSE  # Is this a pair test or not? (TRUE or FALSE)

# Do you need to do gene-level differential expression analysis?
GENE_LEVEL: FALSE  # TRUE or FALSE. But if you are using De Novo assembly or not using ENSEMBL, FALSE is the only option
## If TRUE, specify the corresponding dataset in ENSEMBL for your interested organism
EnsemblDataSet: hsapiens_gene_ensembl  # search for your dataset in the file EnsemblDataSet_look_up_table.csv 

## the comparison(s) you want to do. If multiple comparisons, specify each pair (CONTROL & TREAT) in order respectively
CONTROL: ["Untreated"]
TREAT: ["Dexamethasone"]
## length of 'CONTROL' should agree with that of 'TREAT'
## what you fill in there should agree with the "group" column in metadata.tsv

FILTER:
  yesOrNo: TRUE  # Filter out low expressed genes or not? (TRUE or FALSE)
  tpm: 1  # if yes for filter, what's the threshold of tpm?
